---
title: "NrdR in GTDB"
author: "Ghada Nouairia & Daniel Lundin"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document: 
    toc: yes
  pdf_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, fig.path = 'figures/', cache = TRUE)
ggplot2::theme_set(ggplot2::theme_bw())

# Constants
NRDR_MIN_HMM_COVERAGE = 0.9

# Libraries
library(kfigr)
library(readr)
library(feather)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
```

```{r load-tables}
# DL: We were going to use only representative genomes
accessions <- read_feather("data/pfitmap-gtdb-RNRs.accessions.feather")
# dbsources <- read_feather('data/pfitmap-gtdb-RNRs.dbsources.feather')
# domains <- read_feather('data/pfitmap-gtdb-RNRs.domains.feather')
hmm_profiles <- read_feather('data/pfitmap-gtdb.hmm_profiles.feather')
proteins <- read_feather('data/pfitmap-gtdb-RNRs.proteins.feather')
# sequences <- read_feather('data/pfitmap-gtdb-RNRs.sequences.feather')
taxa <- read_feather('data/pfitmap-gtdb.taxa.feather')
# tblout <- read_feather('data/pfitmap-gtdb-RNRs.tblout.feather')
# domtblout <- read_feather('data/pfitmap-gtdb-RNRs.domtblout.feather')
```

```{r nrdrs-table}
nrdrs <- hmm_profiles %>%
  filter(psuperfamily == 'NrdR-superfamily') %>%
  inner_join(proteins %>% filter((hmm_to - hmm_from + 1)/hmmlen >= NRDR_MIN_HMM_COVERAGE) , by = 'profile') %>%
  inner_join(accessions %>%  select(accno, genome_accno),  by = 'accno') %>%
  inner_join(taxa, by = 'genome_accno') 
```

```{r rnrs-table}
rnrs <- hmm_profiles %>%
  filter(psuperfamily == 'NrdGRE') %>%
  inner_join(proteins %>% select(accno, profile),  by = 'profile') %>%
  inner_join(accessions %>%  select(accno, genome_accno),  by = 'accno') %>%
  inner_join(taxa %>% select(genome_accno, tdomain, tphylum, tclass, torder, tfamily, tgenus, tspecies), by = 'genome_accno') 
```

```{r rnr-class-combs}
# This creates a table with RNR class combinations per genome
rnr_class_combs <- rnrs %>% distinct(genome_accno, pclass) %>%
  pivot_wider(names_from = pclass, values_from = pclass) %>%
  unite(class_comb, NrdA, NrdD, NrdJ, sep = ':', na.rm = TRUE)
```

# Data

DESCRIBE THE DATA, AND GIVE SOME SUMS. WORKS LIKE THIS (check the source code): 

`r nrow(taxa)` genomes were searched and contained at least one RNR protein, i.e. enzyme components, NrdI and NrdR.

```{r nrdrfreq-plot, fig.cap = "Proportion of genomes with NrdR in domains of life."}
nrdr_freq <- nrdrs %>%
  distinct(tdomain, genome_accno) %>%
  group_by(tdomain) %>%
  summarise(nrdr_pres_count = n()) %>%
  inner_join(taxa %>%  group_by(tdomain) %>% summarise(genome_count = n()), by = 'tdomain') %>%
  mutate(proportion = nrdr_pres_count / genome_count)

nrdr_freq %>% ggplot(aes(x=tdomain, y=genome_count, fill=nrdr_pres_count)) +
  geom_bar(stat="identity")+ 
  ylab('Domain of life') +
  xlab('Number of genoems') +
  guides(fill=guide_legend(title="NrdR presence in genomes"))
```

# Results

WRITE SOMETHING ABOUT WHAT YOU FIND IN THE PLOTS. REFER TO PLOTS AND TABLES WITH (check source code) `r figr('genomes-with-nrdr', T, type = 'Figure')`.

```{r genomes-with-nrdr, fig.cap = "Genomes with NrdR in main taxonomic groups."}
# Choose domain of life and taxonomic level
# DL: This should be done with a function which is then called from individual chunks, one for each combination!
domain <- 'Bacteria'
# domain = 'Archaea'
level <- 'tphylum'
# level = 'tclass'

nrdr_by_level <- nrdrs %>%
  filter(tdomain == domain) %>%
  group_by_at(level) %>%
  distinct(genome_accno) %>%
  summarise(nrdr_pres_count = n()) %>%
  full_join(
    taxa %>%
      filter(tdomain == domain) %>%
      group_by_at(level) %>%
      summarise (genome_count = n()),
    by = level
  ) %>%
  replace_na(list(nrdr_pres_count = 0)) %>%
  mutate(proportion = nrdr_pres_count / genome_count) 

# Phyla with no nrdr or nrdr_genomes proportion < 0.01, no single genome phyla
# low_nrdr_phyla = nrdr_by_level %>% filter(proportion < 0.01 & genome_count > 1)

# Phyla with nrdr 
# high_nrdr_phyla = nrdr_by_level %>% filter(proportion > 0.7 & genome_count > 1)

# Output a table to use with anvi'o
# DL: Better to do in a separate script only for this purpose. I think this should
#   be made with `make` as part of the building of the project and the resulting
#   table read by this Rmd.
# nrdr_by_level %>%
#   write_tsv(sprintf("./NrdR_proportions_in_%s_%s.tsv", domain, level))
 
# Plotting 
nrdr_by_level %>% 
  filter(genome_count > 1) %>%
  ggplot(aes_string(x=level, y="genome_count", fill="proportion")) +
  geom_bar(stat="identity") +
  scale_fill_gradient(low = "pink", high = "purple", na.value = NA) +
  ylab('Number of genomes') +
  xlab(sprintf('%s %s', domain, level)) +
  scale_y_log10() +
  guides(fill=guide_legend(title="Proportion of genomes with NrdR")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

```{r nrdr-with-single-rnr, fig.cap = "NrdR presence with single RNR"}
nrdr_srnr <- rnrs %>% 
  group_by(genome_accno) %>% 
  mutate (rnrs_by_genome = n()) %>%
  filter(rnrs_by_genome == 1) %>%
  inner_join(nrdrs %>% transmute(genome_accno, NrdR_accno = accno), by = 'genome_accno') %>%
##124 genomes had more than one NrdR
  # DL: The above kind of fact should go in the running text outside code blocks (inserted with inline code, i.e. within `r `).
  distinct(genome_accno, profile, accno, tdomain, tphylum, tclass, torder, tfamily, tgenus, tspecies) 
    
# Proportion of nrdr with single RNR in the genome (tibble output)
# DL: Again, create a function and call with the different values you want, each within its own chunk.
domain <- 'Archaea'
level <- 'tphylum'

nrdr_srnr_prop <- nrdr_srnr %>%
  filter(tdomain == domain) %>%
  group_by_at(level) %>%
  mutate(count = n()) %>%
  inner_join(
    taxa %>%
      group_by_at(level)%>%
      summarize(genome_by_level = n()),
    by = level
  ) %>%
  mutate(proportion = count / genome_by_level) 

# DL: Don't do table output and plot in the same chunk
nrdr_srnr_prop %>% 
  distinct_at(level) %>%
  inner_join(nrdr_srnr_prop %>% select(proportion) %>% distinct(proportion), by = level)
  
# Plot proportion of NrdR with single RNR on genome by taxonomic level
sublevel <- '' # DL: What should this be set to?
nrdr_srnr_prop %>% 
  filter(tdomain == domain) %>%
  filter(genome_by_level > 1) %>%
  distinct(tphylum, count, tdomain) %>%
  ggplot(aes_string(x="tdomain", y="count", fill=level)) +
  geom_bar(stat="identity") +
  ylab('Number of genomes with NrdR and a single RNR') +
  xlab(sprintf('NrdR with single RNR in %s', domain)) +
  guides(fill=guide_legend(title=sprintf("Distribution by %s", sublevel))) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```
  
```{r nrdr-with-multiple-rnrs, fig.cap = "NrdR presence with multiple RNR"}
nrdr_mrnr <- rnrs %>% 
  group_by(genome_accno) %>% 
  mutate (rnrs_by_genome = n()) %>%
  filter(rnrs_by_genome > 1) %>%
  inner_join(nrdrs %>%  transmute(genome_accno, NrdR_accno = accno),  by = 'genome_accno') %>%
  distinct(genome_accno, profile, accno, tdomain, tphylum, tclass, torder, tfamily, tgenus, tspecies) 
##294 genomes had more than one NrdR
# DL: In the running text, see above
    
# Proportion of nrdr with multiple RNR in the genome (tibble output)
domain <- 'Archaea'
level <- 'tphylum'

nrdr_mrnr_prop <- nrdr_mrnr %>%
  filter(tdomain == domain) %>%
  group_by_at(level) %>%
  mutate(count = n()) %>%
  inner_join(taxa %>% group_by_at(level)%>% summarize(genome_by_level = n()), by = level) %>%
  mutate(proportion = count / genome_by_level) 

# DL: No table output with plots
nrdr_mrnr_prop %>% 
  distinct_at(level) %>%
  inner_join(nrdr_mrnr_prop %>% select(proportion) %>% distinct(proportion), by = level)
  
# Plot proportion of NrdR with multiple RNR on genome by taxonomic level

nrdr_mrnr_prop %>% 
  filter(tdomain == domain) %>%
 filter(genome_by_level > 1) %>%
  distinct(tphylum, proportion) %>%
  ggplot(aes_string(x="tphylum", y="proportion", fill=level)) +
  geom_bar(stat="identity") +
  ylab('Number of genomes with NrdR and multiple RNR') +
  xlab(sprintf('NrdR with multiple RNR in %s', domain)) +
  guides(fill=guide_legend(title=sprintf("%s", sublevel))) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```
  
```{r nrdr-with-different-classes, fig.cap = "NrdR presence with multiple RNR/different classes"}
# Proportion of nrdr with multiple RNR in the genome (tibble output) but from different RNR classes 
# DL: Again, do a function
domain <- 'Archaea'
level <- 'tphylum'

nrdr_drnr <- nrdr_mrnr %>%
  inner_join(hmm_profiles %>% select(profile, pclass), by = 'profile') %>%
  filter(tdomain == domain) %>%
  group_by(genome_accno) %>%
  mutate(pcount= n()) %>%
  ungroup %>%
  distinct(genome_accno, tphylum, pclass, pcount) %>%
  pivot_wider(names_from = pclass, values_from = pcount)
  nrdr_drnr = nrdr_drnr %>% mutate(na_count = rowSums(is.na(nrdr_drnr))) %>%
  filter(na_count < 2)

# Occurence of Nrdr with each rnr class combination
# DL: This can be simplified!
nrdr_drnr %>%
  filter(is.na(NrdD)) %>%
  group_by_at(level) %>%
  mutate(NrdAJ = n()) %>%
  distinct(tphylum, NrdAJ) %>%
  full_join(
    nrdr_drnr %>%
      filter(is.na(NrdJ)) %>%
      group_by_at(level) %>%
      mutate(NrdAD = n()) %>%
      distinct(tphylum, NrdAD),
    by = level
  ) %>%
  full_join(nrdr_drnr %>%
               filter(is.na(NrdA)) %>%
               group_by_at(level) %>%
               mutate(NrdJD = n()) %>%
              distinct(tphylum, NrdJD),
             by = level) %>%
  inner_join(taxa %>%
              group_by_at(level)%>%
              summarize(genome_by_level = n()),
            by = level) %>%
  mutate(NrdAJ_prop = NrdAJ / genome_by_level, NrdAD_prop = NrdAD / genome_by_level, NrdDJ_prop = NrdJD / genome_by_level) 
```
  
```{r nrdr-in-archaea-w-nrda, fig.cap = "NrdR in Archaea with class I RNR"}
level <- 'tphylum'

# NrdR+NrdA combination existed in one Archaeal class in each of the three phyla that had this combination (i.e. looking at phylum level, no variability by tclass was found, so we checked by torder)
sublevel <- 'torder'

nrdr_nrda <- nrdrs %>%
  filter(tdomain == 'Archaea') %>%
  select(genome_accno, level, sublevel, tspecies) %>%
  semi_join(rnrs %>% filter(pclass == 'NrdA'), by = 'genome_accno') %>%
  group_by_at(level) %>%
  mutate(count= n()) %>%
  inner_join(taxa %>% group_by_at(level)%>% summarize(genome_by_level = n()), by = level) %>%
  mutate(proportion = count/genome_by_level) 

# Proportion of genomes with NrdR and NrdA by phylum
# DL: Don't mix table and figure output in the same chunk.
nrdr_nrda %>% distinct(tphylum, count, proportion)

# Plotting NrdR + class I RNR combination by taxonomic level
nrdr_nrda %>% 
  distinct(tphylum, torder, count, genome_by_level, proportion) %>%
  # filter(genome_by_level > 1) %>%
  ggplot(aes_string(x=level, y="proportion", fill=sublevel)) +
  geom_bar(stat="identity") +
  ylab(sprintf('Proportion of %s genomes with NrdR and class I RNR', domain)) +
  xlab(sprintf('%s with NrdR and class I RNR in %s', level, domain)) +
  guides(fill=guide_legend(title=sprintf("%s", sublevel))) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```
  
```{r nrdr-w-rnr-on-same-strand, fig.cap = "Presence of NrdR with RNR on the same strand/operon"}

```
  
```{r nrdr-paralogs, fig.cap = "NrdR paralogs"}

```

